version: '3.9'

services:
  integrations-hub:
    image: ghcr.io/sidneyjfg/integrations-hub:latest
    container_name: integrations-hub
    restart: unless-stopped
    environment:
      # BANCO DE DADOS (GLOBAL)
      DB_HOST_MONITORAMENTO:
      DB_PORT_MONITORAMENTO:
      DB_USER_MONITORAMENTO:
      DB_PASS_MONITORAMENTO:
      DB_NAME_MONITORAMENTO:
      DB_NAME_DADOS:

      # Integra√ß√µes ativas (separadas por v√≠rgula)
      # Ex: anymarket,mercadolivre,pluggto,traycorp
      ACTIVE_INTEGRATIONS:

      # ‚è±Ô∏è CRONS
      CRON_NOTAS_SFTP: "15 01 * * *"
      CRON_NOTAS_ML: "10 01 * * *"
      CRON_PRODUTOS: "23 23 * * *"
      CRON_PEDIDOS: "05 23 * * *"
      # üì£ Notifica√ß√£o global
      GOOGLE_CHAT_WEBHOOK_URL: 

      # ANYMARKET
      ANYMARKET_URL: https://api.anymarket.com.br
      ANYMARKET_GUMGATOKEN: ""
      ANYMARKET_DAYS_TO_FETCH: 1

      FULFILLMENT: "1"
      CONVENCIONAL: "1"
      NO_LOOK_STATUS_TYPE: ""

      NERUS_NOTIFICATION_URL: ""
      NERUS_RECEIVE_NOTIFICATION_URL: ""
      NERUS_OI: ""
      SELLER: Default Seller

      # MERCADO LIVRE
      MERCADOLIVRE_CLIENT_ID:
      MERCADOLIVRE_CLIENT_SECRET:

      # Tokens separados por v√≠rgula (1 para cada CLIENTE_ID)
      MERCADOLIVRE_ACCESS_TOKEN:

      MERCADOLIVRE_REFRESH_TOKEN:

      MERCADOLIVRE_CLIENTE_ID:
      MERCADOLIVRE_STORENOS: 

      MERCADOLIVRE_DAYS_TO_FETCH: 
      MERCADOLIVRE_END_TO_FETCH:
      MERCADOLIVRE_END_SFTP:
      MERCADOLIVRE_IGNORE_SERIE:
      MERCADOLIVRE_MAX_RETRY_COUNT: 5000

      MERCADOLIVRE_DISPONIBILIZA_XML_DIVERGENTE:

      MERCADOLIVRE_SFTP_ENABLED:
      MERCADOLIVRE_SFTP_DIR:
      MERCADOLIVRE_USE_LEDGER:

      MERCADOLIVRE_SFTP_IGNORE_END_FILE:
      MERCADOLIVRE_SFTP_IGNORE_TIPO_NOTA:

      MERCADOLIVRE_IS_VONDER:
      MERCADOLIVRE_SFTP_UID:
      MERCADOLIVRE_SFTP_GID:

      # PLUGGTO
      PLUGGTO_URL: https://api.plugg.to
      PLUGGTO_CLIENT_ID: ""
      PLUGGTO_CLIENT_SECRET: ""
      PLUGGTO_USERNAME: ""
      PLUGGTO_PASSWORD: ""
      PLUGGTO_DAYS_TO_FETCH: "1"
      STORENO: "1"
      NERUS_RECEIVE_ORDER_URL: https://nerus.com.br/api/receive-order

      # TRAYCORP
      TRAY_URL: https://api.tray.com.br
      TRAY_TOKEN: ""
      
      
      PORT: 3000
      TZ: America/Sao_Paulo
    ports:
      - "3000:3000"